run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
  - errcheck
  - exportloopref
  - goconst
  - gocyclo
  - gofmt
  - goimports
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - prealloc
  - staticcheck
  - typecheck
  - unconvert
  - unparam
  - unused
