apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-network-policy-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "cluster-network-policy-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-network-policy-operator.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "cluster-network-policy-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
