operator:
  namespaces:
    # -- Namespaces to exclude. "*" can be used at either the beginning or the end.
    # @default -- Release namespace, `kube-*`
    exclude:
    - ""
    - "kube-*"
    # -- Namespaces to include. "*" can be used at either the beginning or the end.
    # @default -- -
    include: []
  additionalArguments: []

metrics:
  # -- Enable metrics endpoint.
  enable: true
  service:
    # -- Metrics service name.
    # @default -- Based on the release name
    name: ""
    # -- Metrics service type.
    type: ClusterIP
    # -- Metrics service port.
    port: 8080

image:
  repository: ghcr.io/desuuuu/cluster-network-policy-operator
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

priorityClassName: ""

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

resources:
  requests:
    cpu: 20m
    memory: 50Mi
  limits:
    cpu: 50m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
          - arm64
          - ppc64le
          - s390x
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
